def kremlinMapPrint_1_1():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*  Gun              *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *           X          *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_1_2():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*  Gun              *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                X         *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_2_2():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*  Gun              *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*           X                              *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_1_2_second():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                X         *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_1_3():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *            X         *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_1_4():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                 X        *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_1_5():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *             X        *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_2_4():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*          X                               *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

def kremlinMapPrint_2_5():
    print '********************************************'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '*                                          *'
    print '* *******************                      *'
    print '*                   *                      *'
    print '*   Vladimir Putin  *                      *'
    print '*                   *                      *'
    print '*          X        *                      *'
    print '* *******    ********                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*        Guard      *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*********************                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '*                                          *'
    print '*                                          *'
    print '*                   *                      *'
    print '*                   *                      *'
    print '* Garbage can       *                      *'
    print '********************************************'

